openapi: 3.0.1
info:
  title: Deposit Transaction Documents
  description: Enables generation and access to transactions, monthly statements for deposit accounts.
  version: 1.0.0
  x-cortex-type: domain
  x-cortex-tag: deposit-transaction-documents-domain
