openapi: 3.0.1
info:
  title: External Account Linking
  description: |
    Domain responsible for linking customer external bank accounts.
  version: 1.0.0
  x-cortex-type: domain
  x-cortex-tag: external-account-linking-domain
  x-cortex-owners:
  - name: eq-bank-accounts-pod-rw
    type: GROUP
    provider: CORTEX
  - type: EMAIL
    email: gmiranda@eqbank.ca
    description: ""
