openapi: 3.0.1
info:
  title: record-mavericks-team
  x-cortex-tag: record-mavericks-team
  x-cortex-team:
    groups:
    - name: AZ-IDP-RECORD-MAVERICKS
      provider: ACTIVE_DIRECTORY
  x-cortex-type: team
  x-cortex-issues:
    jira:
      projects:
      - name: DB Record Mavericks Pod
        alias: Betterway JIRA - Prod
