openapi: 3.0.1
info:
  title: Customer Chat
  description: Provide customer chat functionality to connect with Backoffice agents.
  version: 1.0.0
  x-cortex-type: domain
  x-cortex-tag: customer-chat-domain
