openapi: 3.0.1
info:
  title: Customer Identity System
  description: Domain responsible for managing and authenticating digital banking user identity.
  version: 1.0.0
  x-cortex-type: domain
  x-cortex-tag: customer-identity-system-domain
